id: IA28F97FD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:38:21+00:00'
last_modified: '2022-06-15T18:44:43.478269+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19449
  title: དངོས་གཞིའི་ཟིན་བྲིས་བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7554':
      image_group_id: I8LS19451
      title: Volume 1 of dngos gzhi'i zin bris byang chub lam gyi sgron me/
      total_pages: 104
      order: 1
      base_file: 7554.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
